
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'LOG LPAREN RPAREN URI\n    tree : LOG LPAREN tree RPAREN tree\n        | URI tree\n        | empty\n    \n\n    empty :\n    '
    
_lr_action_items = {'LOG':([0,3,5,8,],[2,2,2,2,]),'URI':([0,3,5,8,],[3,3,3,3,]),'$end':([0,1,3,4,6,8,9,],[-4,0,-4,-3,-2,-4,-1,]),'LPAREN':([2,],[5,]),'RPAREN':([3,4,5,6,7,8,9,],[-4,-3,-4,-2,8,-4,-1,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'tree':([0,3,5,8,],[1,6,7,9,]),'empty':([0,3,5,8,],[4,4,4,4,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> tree","S'",1,None,None,None),
  ('tree -> LOG LPAREN tree RPAREN tree','tree',5,'p_tree','ldp.py',40),
  ('tree -> URI tree','tree',2,'p_tree','ldp.py',41),
  ('tree -> empty','tree',1,'p_tree','ldp.py',42),
  ('empty -> <empty>','empty',0,'p_empty','ldp.py',53),
]
